### ISSUE TITLE
storing of toolbar items

### ISSUE THREAD

**Issue by pbek** [mbasaglia/Qt-Toolbar-Editor#1]
Thank you for this wonderful library!
I attempt to use it in https://github.com/pbek/QOwnNotes.

Do you by chance know an easy way to store and restoring the modified toolbars?

**Comment by mbasaglia** [comment]
Hi, thanks for trying my library.

You can use the built-in QMainWindow saveState/restoreState methods.
http://doc.qt.io/qt-5/qmainwindow.html#restoreState

**Comment by pbek** [comment]
Thank you for your fast answer! Are you sure about QMainWindow saveState/restoreState? I haven't managed to store QToolBar actions with it yet. It stores a lot, like QDockWidget placement, but I'm not sure about toolbar actions.

**Comment by mbasaglia** [comment]
As far as I know, it does. It's what I used in Knotter, the project from which this library was spawned.

**Comment by pbek** [comment]
This one: https://sourceforge.net/projects/knotter/? Nice! :)

I will retry then! Thanks a lot for your help!

**Comment by mbasaglia** [comment]
Yeah, that. Now it's on GitHub https://github.com/mbasaglia/Knotter

**Comment by pbek** [comment]
I think you are doing a lot more than just `saveState` in Knotter. ;)

``` cpp
void Settings::initialize_window(QMainWindow *w)
{
    if ( !toolbars.empty() && m_save_toolbars )
    {
        foreach(QToolBar* tb, w->findChildren<QToolBar*>() )
            delete tb;
        foreach(const String_Toolbar& tb, toolbars)
            tb.create(w);
    }

    if ( m_save_ui )
    {
        w->restoreGeometry(m_window_geometry);
        w->restoreState(m_window_state);
        w->setIconSize(QSize(m_icon_size,m_icon_size));
        w->setToolButtonStyle(tool_button_style);
    }

    foreach(QAction* action,w->findChildren<QAction*>())
    {
        if ( !action->objectName().isEmpty() )
            m_action_default[action->objectName()] = action->shortcut();
    }

    foreach(QString name, m_actions.keys())
    {
        QAction* action = w->findChild<QAction*>(name);
        if ( action )
            action->setShortcut(m_actions[name]);
    }

}

void Settings::save_window(QMainWindow *w)
{
    toolbars.clear();
    foreach(QToolBar* tb, w->findChildren<QToolBar*>())
        toolbars.append(tb);
    m_icon_size = w->iconSize().width();
    tool_button_style = w->toolButtonStyle();
    m_window_geometry = w->saveGeometry();
    m_window_state = w->saveState();

    m_actions.clear();
    foreach(QAction* action,w->findChildren<QAction*>())
    {
        if ( !action->objectName().isEmpty() )
        {
            m_actions[action->objectName()] = action->shortcut();
        }
    }
}
```

You are building a list of `String_Toolbar` from your toolbars. ;)

**Comment by mbasaglia** [comment]
Well, it's been a while :P 
I guess I store action names.
https://github.com/mbasaglia/Knotter/blob/master/src/string_toolbar.cpp

**Comment by pbek** [comment]
Yes, I already found it. ;)

It's a bit more complex for QOwnNotes. I've also a combo box in in the toolbar and the app modifies the standard toolbars later on, so they must not be removed... I'm working on that.

And I guess I will integrate support for showing all menu items, instead of toolbar items on the left side of the Toolbar_Editor widget, because I don't have all menu items in the toolbars...

**Comment by mbasaglia** [comment]
Sure, feel free to create a pull request if you make improvements.
Also if you find a generic way of serializing the toolbars, I guess it could be included here.

**Comment by pbek** [comment]
> Sure, feel free to create a pull request if you make improvements.

I will!

> Also if you find a generic way of serializing the toolbars, I guess it could be included here.

I haven't found one yet, I now do it in a pretty similar way

**Comment by pbek** [comment]
> And I guess I will integrate support for showing all menu items, instead of toolbar items on the left side of the Toolbar_Editor widget, because I don't have all menu items in the toolbars...

Stupid me, you are exactly doing that... :)
