### ISSUE TITLE
Referencing an unknown file

### ISSUE THREAD

**Issue by ron-popov** [mbasaglia/Qt-Toolbar-Editor#4]
On line 26 of toolbar_editor.hpp you include a file called ui_toolbar_editor.h, but that file is not in that directory and i can't seem to find it. 
Where did that file come from and how can i build the library without that file ?

**Comment by mbasaglia** [comment]
It should be generated by `uic` from src/toolbar_editor.ui as part of the build process.
How are you building it?

**Comment by ron-popov** [comment]
I'm Using QtCreator for working on QOwnNotes , i don't really know how it is being built , but when i build it i get an error that ui_toolbar_editor.h is missing.

**Comment by mbasaglia** [comment]
If you include toolbar_editor.pri from your .pro file, then qmake ensures uic is called at the right time.

**Comment by mbasaglia** [comment]
QOwnNotes uses CMake, and they are setting it up correctly so it should work fine

See https://github.com/pbek/QOwnNotes/blob/d48af3ff1ebcc7d87c99b8a3054802db03473c44/src/CMakeLists.txt#L41-L42

They are using a modified fork of this repo though https://github.com/pbek/Qt-Toolbar-Editor/tree/86d022c26810184cb12e42ccba3b79d2c4b5fe25

In any case, maybe you are better off asking them for help
